eureka:
  client:
    instance:
      preferIpAddress: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
info:
  app:
    description: '...'
    name: ${spring.application.name}
    version: 1.0.0
  author: Luis Eduardo Cochachi Chamorro
  eureka:
    client:
      instance:
        preferIpAddress: ${eureka.client.instance.preferIpAddress}
      serviceUrl:
        defaultZone: ${eureka.client.serviceUrl.defaultZone}
  spring:
    config:
      import: ${spring.config.import}
management:
  endpoints:
    web:
      exposure:
        include: info
  info:
    env:
      enabled: true
mongodb:
  provider0:
    database: mservice3
    password: password
    uri: mongodb://${mongodb.provider1.username}:${mongodb.provider1.password}@127.0.0.1:27017/${mongodb.provider1.database}?ssl=false
    username: user
server:
  port: 0
spring:
  application:
    name: MicroService3
  config:
    import: optional:configserver:http://localhost:8888
logging:
  file:
    name: spring-boot-logging.log
  level:
    guru:
      springframework:
        blogs:
          controllers: INFO
    org:      
      springframework:
        web: INFO